@startuml

scale 0.6

title Cancer Journey – Conceptual Flow

start 
:DIAGNOSIS + FIRST TREATMENT;
:OVERALL TREATMENT RESPONSE;
:EVIDENCE + FOLLOWUP VISIT;
:EVIDENCE + FOLLOWUP VISIT;
:EVIDENCE + FOLLOWUP VISIT (Disease evolution);
:TREATMENT;
:EVIDENCE + FOLLOWUP VISIT;
:EVIDENCE + FOLLOWUP VISIT (Disease evolution);
:PATIENT's DEATH;
stop
@enduml
