@startuml
hide empty members
skinparam classAttributeIconSize 0

class CancerConditionAtDiagnosis {
  patientReference : Reference(CancerPatient) [1..1]
  histologyBehaviour : CodeableConcept [0..1]
  bodySite : CodeableConcept [1..1]
  tumourGradingSystem : CodeableConcept [0..1]
  tumourGradingValue : string [0..1]
  visitDate : dateTime [0..1]
  biopsyDate : dateTime [0..1]
  imagingDate : dateTime [0..1]
  labReportDate : dateTime [0..1]
}

note right of CancerConditionAtDiagnosis
- histologyBehaviour: WG reccomends ICD03, the WG will monitor possible next versions. This attribute becomes mandatory once the cancer has been diagnosed; however, during the diagnostic workup it may still be absent, as the biopsy resulting from the surgery may not yet be available. nan
- bodySite: WG reccomends ICD03, the WG will monitor possible next versions. It is required to choose the most specific code available, meaning the most detailed code in the hierarchical terminology that precisely identifies the body site. nan
- tumourGradingSystem: It represents the classification system used to define the tumor grade, such as Gleason (a grading system for prostate cancer) or FNCLCC (a grading system for soft tissue sarcomas). We need to determine the appropriate cardinality. nan
- tumourGradingValue: It represents the measured grade value based on the specific classification defined in the TumorGradingSystem. We need to determine the appropriate cardinality. nan
- visitDate: At least one of these dates must be present, since the model requires a diagnosis date for the Cancer Condition. nan
end note
@enduml
