@startuml

scale 0.8

title Cancer Journey – Conceptual Flow

start 
:DIAGNOSIS + FIRST TREATMENT;
:EVIDENCE + OVERALL TREATMENT RESPONSE;
:EVIDENCE + FOLLOWUP VISIT;
:EVIDENCE + FOLLOWUP VISIT;
:EVIDENCE + FOLLOWUP VISIT (Disease evolution);
:TREATMENT;
:EVIDENCE + FOLLOWUP VISIT;
:EVIDENCE + FOLLOWUP VISIT (Disease evolution);
:PATIENT's DEATH;
stop
@enduml
