@startuml
hide empty members
skinparam classAttributeIconSize 0

class Imaging {
  type : CodeableConcept [1..1]
  bodySite : CodeableConcept [1..*]
}

note right of Imaging
- type: It represents the type of imaging procedure performed (e.g. thoracic MRI) nan
- bodySite: It represents the body site on which the procedure was performed. nan
end note
@enduml
