@startuml
hide empty members
skinparam classAttributeIconSize 0

class Imaging {
  type : CodeableConcept [1..1]
  type : = [^definition]
  bodySite : CodeableConcept [1..*]
  bodySite : = [^definition]
}

@enduml
