@startuml
hide empty members
skinparam classAttributeIconSize 0

class Surgery {
  subject : CancerPatient [1..1]
  cancerConditionAtDiagnosisReference : Reference(CancerConditionAtDiagnosis) [1..1]
  clinicalCancerProgressionReference : Reference(ClinicalCancerProgression) [0..1]
  intent : CodeableConcept [1..1]
  date : dateTime [1..1]
  bodySite : CodeableConcept [1..*]
}

@enduml
